### ISSUE TITLE
Support the with statement

### ISSUE THREAD

**Issue by arjunguha** [ocelot-ide/Stopify#275]
We've been focused on strict mode, but it would be easy to support the with statement. We simply have to ensure that the object expression does not have any nested applications: that is all.

**Comment by jpolitz** [comment]
Now _that_ is something jumper can do that Pyret, and things like
Regenerator, cannot.

Interesting!
​

**Comment by arjunguha** [comment]
right. you'd have to desugar with statements. terrible.

**Comment by jpolitz** [comment]
I don't know who would ever do that.

**Comment by arjunguha** [comment]
I am going to close this issue. This was a good joke.
