### ISSUE TITLE
Data race bug in PLISS demo

### ISSUE THREAD

**Issue by donald-pinckney** [ocelot-ide/Stopify#461]
The following shows the bug:

```
let x = {};
console.log(x);
x.stuff = 1234;
```

This prints `{stuff: 1234}`, which is incorrect.

**Comment by arjunguha** [comment]
this does not affect Ocelot. Only occurs on the PLISS demo site. Regardless, it is a bug.

**Comment by arjunguha** [comment]
Run the following variation with developer tools open:
```
let x = {};
debugger;
console.log(x);
x.stuff = 1234;
```

If you step through execution, you'll see that the calll to `appendLog` is queued to run on the next turn, which is after the `x.stuff =1234` occurs:

https://github.com/ocelot-ide/Stopify/blob/master/continuations-playground/ts/index.tsx#L7

The solution is to either:
1. Force the console.log to occur immediately (I don't know how to do that), or
2. Append to the log a deep copy of x, which is a pain to do.

Strictly speaking, this is not a Stopify bug. It's not worth fixing the bug in the PLISS demo site.
