### ISSUE TITLE
Website Navigation is inconsistant.

### ISSUE THREAD

**Issue by LeifAndersen** [ocelot-ide/Stopify#482]
If from the homepage, you click on `Documentation` in the navbar, you go to this github repo.

However, if from the homepage, you click `FAQ` in the navbar, and then click `Documentation` in the navbar, you go to the ReadTheDocs page.

I suspect the first case is a mistake, but either way the navbar should probably at least be consistent. ;)

**Comment by arjunguha** [comment]
Thanks, fixed.
