### ISSUE TITLE
Window object does not affect global enviroment in stopify.

### ISSUE THREAD

**Issue by LeifAndersen** [ocelot-ide/Stopify#487]
This is probably something that a babel transformation can handle, but right now, changes to the window object don't seem to affect the global environment. For example, the following program prints undefined in the stopify sandbox on https://www.stopify.org/:

```
window.freename = 42;
console.log(freename);  // => undefined, should be 42
```

In that sandbox, it looks like `window` is given to `.g`, as this program does work:

```
window.freename = 42;
console.log(window.freename); // => 42
```

To be fair though, this may be a feature you wanted, and a babel translation might be able to transform all free variables to accesses on whatever `window` object was added.

**Comment by LeifAndersen** [comment]
(To be fair though, I could be missing something obvious here, since the `window` object in javascript is wild.)

**Comment by arjunguha** [comment]
Yeah, this is deliberate. To the the behavior you want, do this:

```
let runner = stopifyLocally(...);
runner.g.window = runner.g; // makes the wild window
runner.start
```

**Comment by LeifAndersen** [comment]
Ah, that makes sense. Thanks.
