### ISSUE TITLE
Demo on stopify.org fails to run if modified

### ISSUE THREAD

**Issue by LeifAndersen** [ocelot-ide/Stopify#493]
This may only be a bug with the clojure option, but the example on stopify.org fails to run when you modify it at all.

Steps to reproduce:

1. Go to https://stopify.org
2. Set the language to `ClojureScript`
3. Change line 6 from `(println (tail_sum 1000000 1))` to `(println (tail_sum 100000 1))` (I removed one `0`.)
4. Click run, see that nothing prints out.

If you remove step 3 it does print as expected.

**Comment by arjunguha** [comment]
Fixed. Network error.
